[package]
name = "hesychiamids"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "A Rust-based MIDI player with an integrated piano roll view."

[dependencies]
eframe = "0.29"
egui = "0.29"
midly = { version = "0.5", features = ["std"] }
anyhow = "1.0"
rfd = "0.14"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
rodio = "0.15"
rustysynth = "1"
cpal = "0.15"