name = "fire"
description = "由用户自定义创建"

[settings]
piano_bg_r = 75
piano_bg_g = 5
piano_bg_b = 0
white_key_r = 200
white_key_g = 0
white_key_b = 0
black_key_r = 35
black_key_g = 0
black_key_b = 0
note_r = 255
note_g = 185
note_b = 35
active_note_r = 255
active_note_g = 100
active_note_b = 20
text_r = 255
text_g = 255
text_b = 0
cursor_r = 255
cursor_g = 255
cursor_b = 0
grid_bright_r = 255
grid_bright_g = 0
grid_bright_b = 0
grid_dim_r = 255
grid_dim_g = 105
grid_dim_b = 0
pitch_min = 60
pitch_range = 40
time_zoom = 0.15000000596046448
follow_playhead = true
show_cursor = true
enable_audio = false
layout_orientation = "Horizontal"
horizontal_keyboard_width = 74.39999389648438
vertical_keyboard_height = 80.0
vertical_black_key_offset = 0.5
vertical_black_key_width_scale = 0.8999999761581421
