name = "forest"
description = "阳光穿过叶隙"

[settings]
piano_bg_r = 125
piano_bg_g = 255
piano_bg_b = 210
white_key_r = 125
white_key_g = 240
white_key_b = 220
black_key_r = 0
black_key_g = 255
black_key_b = 190
note_r = 0
note_g = 255
note_b = 110
active_note_r = 50
active_note_g = 145
active_note_b = 0
text_r = 0
text_g = 145
text_b = 255
cursor_r = 40
cursor_g = 190
cursor_b = 90
grid_bright_r = 170
grid_bright_g = 182
grid_bright_b = 225
grid_dim_r = 40
grid_dim_g = 185
grid_dim_b = 130
pitch_min = 60
pitch_range = 48
time_zoom = 0.4699999988079071
follow_playhead = true
show_cursor = true
enable_audio = true
layout_orientation = "Horizontal"
horizontal_keyboard_width = 74.39999389648438
vertical_keyboard_height = 80.0
vertical_black_key_offset = 0.5
vertical_black_key_width_scale = 0.8999999761581421
