name = "pink_night"
description = "由用户自定义创建"

[settings]
piano_bg_r = 200
piano_bg_g = 22
piano_bg_b = 177
white_key_r = 240
white_key_g = 150
white_key_b = 240
black_key_r = 190
black_key_g = 40
black_key_b = 185
note_r = 255
note_g = 0
note_b = 255
active_note_r = 255
active_note_g = 200
active_note_b = 255
text_r = 255
text_g = 75
text_b = 255
cursor_r = 255
cursor_g = 95
cursor_b = 255
grid_bright_r = 255
grid_bright_g = 180
grid_bright_b = 255
grid_dim_r = 100
grid_dim_g = 0
grid_dim_b = 120
pitch_min = 60
pitch_range = 40
time_zoom = 0.15000000596046448
follow_playhead = true
show_cursor = true
enable_audio = false
layout_orientation = "Horizontal"
horizontal_keyboard_width = 74.39999389648438
vertical_keyboard_height = 80.0
vertical_black_key_offset = 0.5
vertical_black_key_width_scale = 0.8999999761581421
