name = "pink_light"
description = "夏花绚烂"

[settings]
piano_bg_r = 180
piano_bg_g = 112
piano_bg_b = 255
white_key_r = 227
white_key_g = 170
white_key_b = 240
black_key_r = 255
black_key_g = 140
black_key_b = 230
note_r = 255
note_g = 175
note_b = 240
active_note_r = 255
active_note_g = 102
active_note_b = 255
text_r = 0
text_g = 95
text_b = 255
cursor_r = 160
cursor_g = 100
cursor_b = 255
grid_bright_r = 255
grid_bright_g = 100
grid_bright_b = 255
grid_dim_r = 165
grid_dim_g = 60
grid_dim_b = 142
pitch_min = 60
pitch_range = 40
time_zoom = 0.019999999552965164
follow_playhead = true
show_cursor = true
enable_audio = false
layout_orientation = "Horizontal"
horizontal_keyboard_width = 74.39999389648438
vertical_keyboard_height = 80.0
vertical_black_key_offset = 0.5
vertical_black_key_width_scale = 0.8999999761581421
