name = "simple_light"
description = "由用户自定义创建"

[settings]
piano_bg_r = 255
piano_bg_g = 255
piano_bg_b = 255
white_key_r = 255
white_key_g = 255
white_key_b = 255
black_key_r = 0
black_key_g = 0
black_key_b = 0
note_r = 255
note_g = 255
note_b = 255
active_note_r = 0
active_note_g = 0
active_note_b = 0
text_r = 0
text_g = 0
text_b = 0
cursor_r = 255
cursor_g = 255
cursor_b = 255
grid_bright_r = 255
grid_bright_g = 255
grid_bright_b = 255
grid_dim_r = 255
grid_dim_g = 255
grid_dim_b = 255
pitch_min = 40
pitch_range = 48
time_zoom = 0.5
follow_playhead = false
show_cursor = true
enable_audio = true
layout_orientation = "Vertical"
horizontal_keyboard_width = 50.0
vertical_keyboard_height = 104.39996337890625
vertical_black_key_offset = 0.5
vertical_black_key_width_scale = 0.8999999761581421
